import { Router } from "express";
import * as photographerController from "./photographer.controller.js";
import fileUpload, { fileValidation } from "../../services/multer.js";
import { asyncHandler } from "../../services/errorHandling.js";
import { endPoint } from "./photographer.endpoint.js";
import { auth } from "../../middleware/auth.js";
import { validation } from "../../middleware/validation.js";
import * as validators from "./photographer.validation.js";
const router = Router();
router.post( "/insertPhotographer",validation(validators.appointment),auth(endPoint.insert),fileUpload(fileValidation.image).single("image"),asyncHandler(photographerController.insertPhotographer));
router.get("/getPhotographers",auth(endPoint.get),asyncHandler(photographerController.getPhotographers));
router.delete("/deletePhotographer/:id",auth(endPoint.delete),photographerController.deletePhotographer);
router.put("/addAppointments/:id",validation(validators.appointment ),auth(endPoint.appointment),asyncHandler(photographerController.addAppointments));
export default router;
